fullscreen=yes
speed=2
mute=yes
start=7
hwdec=auto
hwdec-codecs=all

# Set uosc's autoload option to no (To prevent it from not closing automatically after playback ends)
script-opts=uosc-autoload=no

[pause_on_focus_lost_video]
profile-cond=not focused and get('current-tracks/video/image') == false
profile-restore=copy
pause=yes
