version: '3.7'

services:
  clash:
    image: dreamacro/clash:latest
    container_name: clash
    restart: always
    volumes:
      - ~/.config/clash:/root/.config/clash
    ports:
      - 7890:7890
      - 7891:7891
      - 9090:9090

  clash_dashboard:
    image: haishanh/yacd:latest
    container_name: clash_dashboard
    restart: always
    depends_on:
      - clash
    ports:
      - 9091:80
